Listen 8443
<VirtualHost _default_:8443>
  DocumentRoot "D:\ketan\github\uniservernxt\uniwamp\www"
  ServerName localhost:8443
  SSLEngine on
  SSLCertificateFile "D:\ketan\github\uniservernxt\uniwamp\ssl\server.crt"
  SSLCertificateKeyFile "D:\ketan\github\uniservernxt\uniwamp\ssl\server.key"
  ErrorLog "D:\ketan\github\uniservernxt\uniwamp\logs\apache-ssl-error.log"
  CustomLog "D:\ketan\github\uniservernxt\uniwamp\logs\apache-ssl-access.log" common
</VirtualHost>
