Listen 8443
<VirtualHost _default_:8443>
  DocumentRoot "D:\ketan\github\uniwamp\www"
  ServerName localhost:8443
  SSLEngine on
  SSLCertificateFile "D:/ketan/github/uniwamp\ssl\server.crt"
  SSLCertificateKeyFile "D:/ketan/github/uniwamp\ssl\server.key"
  ErrorLog "D:/ketan/github/uniwamp\logs\apache-ssl-error.log"
  CustomLog "D:/ketan/github/uniwamp\logs\apache-ssl-access.log" common
</VirtualHost>
