# Managed by UniWamp
<VirtualHost *:8080>
  ServerName localhost
  ServerAlias 127.0.0.1 localhost
  DocumentRoot "D:\ketan\github\uniwamp\www"
  <Directory "D:\ketan\github\uniwamp\www">
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName myproject
  DocumentRoot "D:\ketan\github\uniwamp\www\myproject"
  <Directory "D:\ketan\github\uniwamp\www\myproject">
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName myproject2
  DocumentRoot "D:\ketan\github\uniwamp\www\myproject2"
  <Directory "D:\ketan\github\uniwamp\www\myproject2">
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>


