# Managed by UniWamp
<VirtualHost *:8080>
  ServerName localhost
  ServerAlias 127.0.0.1 localhost
  DocumentRoot "D:\ketan\github\uniwamp\www"
  <Directory "D:\ketan\github\uniwamp\www">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName myproject2
  DocumentRoot "D:\ketan\github\uniwamp\www\myproject2"
  <Directory "D:\ketan\github\uniwamp\www\myproject2">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara22
  DocumentRoot "D:\ketan\github\uniwamp\www\lara22"
  <Directory "D:\ketan\github\uniwamp\www\lara22">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara44
  DocumentRoot "D:\ketan\github\uniwamp\www\lara44\public"
  <Directory "D:\ketan\github\uniwamp\www\lara44\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara31
  DocumentRoot "D:\ketan\github\uniwamp\www\lara31\public"
  <Directory "D:\ketan\github\uniwamp\www\lara31\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara55
  DocumentRoot "D:\ketan\github\uniwamp\www\lara55\public"
  <Directory "D:\ketan\github\uniwamp\www\lara55\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara111
  DocumentRoot "D:\ketan\github\uniwamp\www\lara111\public"
  <Directory "D:\ketan\github\uniwamp\www\lara111\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName ketan
  DocumentRoot "D:\ketan\github\uniwamp\www\ketan\public"
  <Directory "D:\ketan\github\uniwamp\www\ketan\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName laralara
  DocumentRoot "D:\ketan\github\uniwamp\www\laralara\public"
  <Directory "D:\ketan\github\uniwamp\www\laralara\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>


