# Managed by UniWamp
<VirtualHost *:8080>
  ServerName localhost
  ServerAlias 127.0.0.1 localhost
  DocumentRoot "D:\ketan\github\uniwamp\www"
  <Directory "D:\ketan\github\uniwamp\www">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara44
  DocumentRoot "D:\ketan\github\uniwamp\www\lara44\public"
  <Directory "D:\ketan\github\uniwamp\www\lara44\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara31
  DocumentRoot "D:\ketan\github\uniwamp\www\lara31\public"
  <Directory "D:\ketan\github\uniwamp\www\lara31\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName lara55
  DocumentRoot "D:\ketan\github\uniwamp\www\lara55\public"
  <Directory "D:\ketan\github\uniwamp\www\lara55\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName laraveltest
  DocumentRoot "D:\ketan\github\uniwamp\www\laraveltest\public"
  <Directory "D:\ketan\github\uniwamp\www\laraveltest\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName backdropcms
  DocumentRoot "D:\ketan\github\uniwamp\www\backdropcms"
  <Directory "D:\ketan\github\uniwamp\www\backdropcms">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:8080>
  ServerName concretecms
  DocumentRoot "D:\ketan\github\uniwamp\www\concretecms\public"
  <Directory "D:\ketan\github\uniwamp\www\concretecms\public">
    AllowOverride All
    DirectoryIndex index.php index.html
    Require all granted
  </Directory>
</VirtualHost>


