[PHP]
display_errors=On
error_reporting=E_ALL
log_errors=On
short_open_tag=Off
expose_php=Off
memory_limit=256M
upload_max_filesize=32M
post_max_size=32M
max_execution_time=120
max_input_vars=3000
extension_dir="D:\ketan\github\uniwamp\runtime\php\php83\ext"
extension=php_bz2.dll
extension=php_curl.dll
extension=php_exif.dll
extension=php_fileinfo.dll
extension=php_ftp.dll
extension=php_gd.dll
extension=php_gettext.dll
extension=php_imap.dll
extension=php_intl.dll
extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_mysqli.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll
extension=php_sqlite3.dll
extension=php_zip.dll

upload_tmp_dir="D:\ketan\github\uniwamp\tmp"
sys_temp_dir="D:\ketan\github\uniwamp\tmp"
error_log="D:\ketan\github\uniwamp\logs\php-error.log"