[PHP]
display_errors=On
error_reporting=E_ALL
log_errors=On
short_open_tag=Off
expose_php=Off
memory_limit=256M
upload_max_filesize=32M
post_max_size=32M
max_execution_time=120
max_input_vars=3000
extension_dir="D:\ketan\github\uniservernxt\uniwamp\runtime\php\php85\ext"

upload_tmp_dir="D:\ketan\github\uniservernxt\uniwamp\tmp"
sys_temp_dir="D:\ketan\github\uniservernxt\uniwamp\tmp"
error_log="D:\ketan\github\uniservernxt\uniwamp\logs\php-error.log"